default:
  image: node:13
  before_script:
    - yarn install
  cache:
    paths:
      - node_modules/
      - .yarn

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - yarn test

pages:
  stage: deploy
  script:
    - yarn build
    - rm public -rf # for some reason gitlab only allows a folder named public
    - mkdir public
    - cp dist/* public/ -r
  artifacts:
    paths:
      - public
  only:
    - master
