image: node:13

pages:
  script:
    - yarn install
    - yarn build
    - rm public -rf # for some reason gitlab only allows a folder named public
    - mkdir public
    - cp dist/* public/ -r
  artifacts:
    paths:
      - public
  only:
    - master
