default:
  image: node:13
  before_script:
    - yarn install
  cache:
    paths:
      - node_modules/

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - yarn ci
  coverage: /All\sfiles.*?\s+(\d+.\d+)/

pages:
  stage: deploy
  script:
    - yarn build
    - rm public -rf # for some reason gitlab only allows a folder named public
    - mkdir public
    - cp dist/* public/ -r
    # gziped delivery with gitlab pages is a little more hands-on https://webd97.de/post/gitlab-pages-compression/
    - gzip -k -6 $(find public -type f)
  artifacts:
    paths:
      - public
  only:
    - master
